# Generated by Django 3.1.4 on 2020-12-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctlisting_bidslisting_commentslisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctlisting',
            name='description',
            field=models.CharField(default='Description', max_length=200),
        ),
        migrations.AddField(
            model_name='auctlisting',
            name='starting_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auctlisting',
            name='title',
            field=models.CharField(default='Product', max_length=64),
        ),
    ]
