# Generated by Django 3.1.4 on 2020-12-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_article_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctlisting',
            name='user_name',
            field=models.CharField(default='Anonynous', max_length=64),
        ),
    ]
