# Generated by Django 3.1.4 on 2020-12-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctlisting_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctlisting',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=64),
        ),
    ]
