# Generated by Django 3.1.4 on 2020-12-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201231_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctlisting',
            name='comments',
        ),
        migrations.AddField(
            model_name='auctlisting',
            name='comments_title',
            field=models.ManyToManyField(to='auctions.commentsListing'),
        ),
        migrations.AddField(
            model_name='commentslisting',
            name='comments',
            field=models.CharField(default='no comments yet.', max_length=200),
        ),
    ]
