# Generated by Django 3.1.4 on 2020-12-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201231_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctlisting',
            name='comments_title',
            field=models.ManyToManyField(related_name='comment_comment', to='auctions.commentsListing'),
        ),
    ]
